### ISSUE TITLE
question: timeout for q8384

### ISSUE THREAD

**Issue by LunarLanding** [timrae/drivepy#1]
Hi, I'm researching ways to control the q8384 optical spectrum analyzer, and I noticed that in https://github.com/timrae/drivepy/blob/master/advantest/spectrumanalyzer.py
you set a timeout of 20mn (btw the command sequence you used seems useful).
Is the data retrieval delay really in the order of minutes? Knowing this would help me decide whether or not I should prioritize a faster equipment.

**Comment by timrae** [comment]
Hi it's not the data retrieval delay but the measurement time. And that
completely depends on the resolution, sensitivity, and span that you need.
In my case I needed all 3 very large so I had to maximize everything which
resulted in sweep times on the order of ten+ minutes. If you have a very
strong signal then the same measurement would take less than 30 seconds.

In the end I switched to a spectrometer with line array detector instead
which is much faster for my purpose, though you lose many conveniences of
an OSA.

The command sequence is basically the same as the example in the manual!

I hope you find the repository useful

**Comment by LunarLanding** [comment]
Thanks!  I'm still figuring out what kind of connector I'm gonna use
though... gpib to usb are expensive but can connect to a laptop,  which
would be nice for development. I've read some stuff about using an arduino
and linux-gpib though!

**Comment by timrae** [comment]
Most people use the NI GPIB-USB-HS. I think it's about $800 new but you can
get one much cheaper from ebay.
